### ISSUE TITLE
Optional unigrams

### ISSUE THREAD

**Issue by danijel3** [jonatasgrosman/huggingsound#19]
According to the type hints in the KenshoLMDecoder initialization routine, the unigram path argument is optional, but the code still crashes if it is not provided.

A simple fix is to add the line:

```
self.unigrams = None
```

somewhere before the line [here](https://github.com/jonatasgrosman/huggingsound/blob/939162daeca81bc2ef0be664133998a6edcb5f75/huggingsound/speech_recognition/decoder.py#L678):

```
        if self.unigrams_path is not None:
```

**Comment by jonatasgrosman** [comment]
Hi @danijel3!
I've just fixed this issue. Thanks for debugging this :)
