### ISSUE TITLE
Pre-trained uppercase models don't work

### ISSUE THREAD

**Issue by nkaenzig** [jonatasgrosman/huggingsound#20]
First of all thanks for this great library, it's really helpful :)

I just tried to fine-tune a model by facebook that they previously fine-tuned on English transcription tasks: `facebook/wav2vec2-large-960h-lv60-self`.

During the training I get WERs of 100%, and after training, `model.transcribe()` returns empty results.

The issue seems to be that this model was trained with a upper-case character vocabulary.

To overcome this, I found this very easy fix, which just converts the vocabulary of the encoder/decoder to lower case:

```
from huggingsound import TrainingArguments, ModelArguments, SpeechRecognitionModel, TokenSet
model = SpeechRecognitionModel(model_name, device='cuda')

model.processor.tokenizer.encoder = {k.lower(): v for k, v in model.processor.tokenizer.encoder.items()}
model.processor.tokenizer.decoder = {k: v.lower() for k, v in model.processor.tokenizer.decoder.items()} 
```

Would be great to integrate this somehow into the library.

**Comment by jonatasgrosman** [comment]
Hi @nkaenzig, I've made some adjustments that fix that, plz upgrade the library and check if this problem is still happening :)

**Comment by nkaenzig** [comment]
seems to work now, thanks :)
