### ISSUE TITLE
'CTCTrainer' object has no attribute 'use_amp'

### ISSUE THREAD

**Issue by its-ogawa** [jonatasgrosman/huggingsound#45]
Use the latest huggingsound.
```
#!pip list | grep huggingsound
huggingsound 0.1.4
```

AttributeError occurs when finetune is performed as shown in the sample below.
https://github.com/jonatasgrosman/huggingsound#fine-tuning

> /usr/local/lib/python3.7/dist-packages/huggingsound/trainer.py in training_step(self, model, inputs)
> 432 inputs = self._prepare_inputs(inputs)
> 433 
> --> 434 if self.use_amp:
> 435 with torch.cuda.amp.autocast():
> 436 loss = self.compute_loss(model, inputs)
> 
> AttributeError: 'CTCTrainer' object has no attribute 'use_amp'

Can you find the cause?

**Comment by its-ogawa** [comment]
It is not a correct solution, but I removed `use_amp` from the source code. That is, I commented it out and ran it.
https://github.com/jonatasgrosman/huggingsound/blob/main/huggingsound/trainer.py

```
        #if self.use_amp:
        # with torch.cuda.amp.autocast():
        # loss = self.compute_loss(model, inputs)
        #else:
            loss = self.compute_loss(model, inputs)
```

```
        #if self.use_amp:
        #self.scaler.scale(loss).backward()
        #elif self.deepspeed:
        if self.deepspeed:
            self.deepspeed.backward(loss)
        else:
            loss.backward()
```

This is a completely reckless response, and I hope you can point me to the correct way to handle this.

I don't know if this is the cause or not, but I am having a problem where evaluate fails for a finetuned model in this state.
I hope you can refer to this as well.
cf. https://github.com/jonatasgrosman/huggingsound/issues/46

**Comment by arikhalperin** [comment]
It's related to transformers version. I use the latest transformers, the correct fix is to use: use_cuda_amq

**Comment by its-ogawa** [comment]
Thanks for answering.

What version of Transformer do you have?
And how did you install it and how did you install it?

**Comment by arikhalperin** [comment]
transformers==4.21.1
pip install transformers

**Comment by nkaenzig-aifund** [comment]
transformers changed the name of the Trainer property `use_amp` to `use_cuda_amp` in this PR:
https://github.com/huggingface/transformers/pull/17138

Use transformers==4.19.2 or rename the variable as suggested by [arikhalperin](https://github.com/arikhalperin)
