### ISSUE TITLE
Fine-tuned version of model - a raised exception

### ISSUE THREAD

**Issue by egorsmkv** [jonatasgrosman/huggingsound#5]
Hello. 

I am getting the following exception:

```
ValueError: Not fine-tuned model! Please, fine-tune the model first.
```

I have looked into the code and see that it needs to have Wav2Vec2ForPreTraining (self.model_config.architectures) in the ctc_finetuded_architectures variable.

Now this variable has these values:

{'WavLMForCTC', 'HubertForCTC', 'UniSpeechSatForCTC', 'Wav2Vec2ForCTC', 'UniSpeechForCTC', 'SEWForCTC', 'SEWDForCTC'}

I am running the code with this model - https://huggingface.co/Yehor/wav2vec2-xls-r-300m-uk-with-lm

I disabled the code that raises that exception and it seems there is no issue.

I would like to use some type of configuration to be able to run the code without changing the library code.

**Comment by jonatasgrosman** [comment]
Upgrade the library and try to reproduce the error again. I've just changed the code, and that issue is maybe fixed now.

**Comment by egorsmkv** [comment]
Now it works correctly. Thank you!
