### ISSUE TITLE
Compability with python 3.10

### ISSUE THREAD

**Issue by FredHaa** [jonatasgrosman/huggingsound#57]
This package cannot be installed with python 3.10.

Trying to install the wheel manually it complains about the correct numba version not being available.
Is numba<0.54.0,>=0.53.1 really required instead e.g. numba==0.55.0 or any other version which is available for python 3.10?

I would love to use this library, but currently it does not seem to be possible to install it on Ubuntu 22.04.

**Comment by frankiedrake** [comment]
Same here

**Comment by warsameF** [comment]
I get this error when installing from pip:


> ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.7,<3.10; 0.1.0 Requires-Python >=3.7,<3.10; 0.1.1 Requires-Python >=3.7,<3.10; 0.1.2 Requires-Python >=3.7,<3.10; 0.1.3 Requires-Python >=3.7,<3.10; 0.1.4 Requires-Python >=3.7,<3.10; 0.1.5 Requires-Python >=3.7,<3.10
> ERROR: Could not find a version that satisfies the requirement huggingsound (from versions: none)
> ERROR: No matching distribution found for huggingsound

**Comment by jonatasgrosman** [comment]
Hi @FredHaa @frankiedrake @garaw7

I've just upgraded some dependencies that might have fixed this issue. Test the latest version of huggingsound and let me know if the problem persists.

**Comment by FredHaa** [comment]
It works now on python 3.10!

Any reason to explicitly not support pytorch 1.13?

**Comment by jonatasgrosman** [comment]
> It works now on python 3.10!
> 
> Any reason to explicitly not support pytorch 1.13?

@FredHaa I'm having some troubles when trying to install torch 1.13 with the other huggingsound dependencies on my machine, so I prefer to put this restriction for now. Still, I'll probably remove this restriction in the future if I realize what's happening in my environment.
